### ISSUE TITLE
Pregunta sobre licencia

### ISSUE THREAD

**Issue by AlbertoCasasOrtiz** [pablocastilla/angiogenesis-analyzer#15]
Hello!

Me gustaría usar este código para analizar imágenes de angiogénesis (entorno académico) como alternativa al plugin de ImageJ, por lo que he creado un fork y estoy adaptando el código a mis imágenes. Ya lo tengo funcionando en Python 3.10 (PyCharm) y he actualizado las dependencias. He obtenido buenos resultados en mis imágenes.

Sin embargo, he notado que el repositorio no tiene licencia, así que no se si puedo utilizarlo para mi investigación. ¿Puedo usar este repositorio en academia, para papers científicos? ¿En el caso de que si, tienes alguna preferencia a la hora de citar el código, o solamente cito el repositorio?

Seria ideal si este repositorio tuviera alguna licencia de software libre para que la comunidad científica pueda utilizarlo y aportar al mismo. Recomendaría utilizar la licencia MIT o BSD. Si lo prefieres, puedo hacer un PR con la licencia.

Un saludo,
Alberto.

**Comment by pablocastilla** [comment]
Buenas Alberto.

Pues me encanta que uses el código. ¿Puedo preguntar sobre qué va la investigación? Por saber a lo que estoy ayudando.

Como veo que de licencias estás mejor que yo si puedes hazme la PR con la misma y la admito del tirón. Es más, no sé muy bien cómo se hará eso, pero si quieres te hago administrador o lo que sea del repositorio para que vaya avanzando, no eres el primero que se interesa por él.

Un saludo.

**Comment by AlbertoCasasOrtiz** [comment]
Muchas Gracias Pablo!

Por supuesto, estamos estudiando el efecto de cannabinoides sintéticos en la vasculatura usando un modelo de ipsc de células endoteliales.

Yo creo que una licencia que puede funcionar bien aquí seria algo permisivo como MIT o BSD, ya que permitiría el uso, modificación y distribución del software, sin hacer responsable a los creadores, pero con la condición de que se incluya el aviso de derechos de autor (si en el aviso de derechos de autor pones tu nombre, es una forma de atribución). Si quieres algo mas restrictivo, podríamos ir a una GPL, que además impone la condición de que obras derivadas sean también GPL, que protege un poco mas contra el uso en software privativo.

Dime cual prefieres y hago un PR con la licencia.

**Comment by pablocastilla** [comment]
Pues mira, si te viene bien a ti mejor la GPL, así los derivados también tienen que ser libres.

¡Muchas suerte con la investigación!

**Comment by AlbertoCasasOrtiz** [comment]
Perfecto, muchas gracias!

Acabo de crear un PR con la licencia. He añadido fecha de creación, fecha actual y tu nombre en la nota de copyright para que se te de crédito por la creación en todo uso, modificación, distribución etc
